strategy:
  type: copy
  volume_ratio: 1
  target:
    driver: rubykube
    market: 'ETHUSDT'
    host: "https://demo.zsmart.tech"
    key: "10bd360617e78745"
    secret: "bd412fd51363076e07a28e28730a2a99"
    limit_book: 500
    rate_limit: 5
  sources:
    - driver: binance
      market: 'ETHUSDT'
      host: "api.binance.com"
      key: ""
      secret: ""
      rate_limit: 1
