log_level: INFO

exchanges:
  - id: 1
    driver: zsmart
    host: "https://demo.zsmart.tech"
    ws: "wss://demo.zsmart.tech/api/v2/websocket"
    key: "dd0dfe1b6857e757"
    secret: "1d34e4a29adb1eec90c24811e97b445d"

  - id: 2
    driver: binance
    host: "https://www.binance.com"
    ws: "wss://stream.binance.com:9443/ws"
    key: ""
    secret: ""

strategies:
  - type: copy
    volume_ratio: 0.3
    delay: 12
    reload: 4
    spread_bids: 10
    spread_asks: 10
    limit_depth: 100
    target:
      exchange_id: 1
      market:
        id: BTCUSDT
        base: BTC
        quote: USDT
        base_precision: 2
        quote_precision: 6
        min_amount: 0.000001
    source:
      exchange_id: 2
      market:
        id: BTCUSDT
        base: BTC
        quote: USDT
        base_precision: 2
        quote_precision: 6
  - type: copy
    volume_ratio: 0.25
    delay: 10
    reload: 5
    spread_bids: 1
    spread_asks: 1
    limit_depth: 100
    target:
      exchange_id: 1
      market:
        id: ETHUSDT
        base: ETH
        quote: USDT
        base_precision: 2
        quote_precision: 5
        min_amount: 0.00001
    source:
      exchange_id: 2
      market:
        id: ETHUSDT
        base: ETH
        quote: USDT
        base_precision: 2
        quote_precision: 5
  - type: trade
    trade_amount: 0.5
    delay: 4
    target:
      exchange_id: 1
      market: 
        id: ETHUSDT
        base: ETH
        quote: USDT
        base_precision: 2
        quote_precision: 5
        min_amount: 0.00001
    source:
      exchange_id: 2
      market:
        id: ETHUSDT
        base: ETH
        quote: USDT
        base_precision: 2
        quote_precision: 5
  - type: trade
    trade_amount: 0.05
    delay: 4
    target:
      exchange_id: 1
      market: 
        id: BTCUSDT
        base: BTC
        quote: USDT
        base_precision: 2
        quote_precision: 6
        min_amount: 0.00001
    source:
      exchange_id: 2
      market:
        id: BTCUSDT
        base: BTC
        quote: USDT
        base_precision: 2
        quote_precision: 6
