log_level: INFO

exchanges:
  - id: 1
    driver: zsmart
    host: "https://demo.zsmart.tech"
    ws: "wss://demo.zsmart.tech/api/v2/websocket"
    key: "d1f1b64597a0bc76"
    secret: "30898636f2bbbe5352230638c838d226"

  - id: 2
    driver: binance
    host: "https://www.binance.com"
    ws: "wss://stream.binance.com:9443/ws"
    key: ""
    secret: ""

strategies:
  - type: copy
    volume_ratio: 1
    delay: 30
    reload: 1
    spread_bids: 0
    spread_asks: 0
    limit_depth: 100
    target:
      exchange_id: 1
      market: 
        id: BTCUSDT
        base: BTC
        quote: USDT
        base_precision: 2
        quote_precision: 6
        min_ask_amount: 0.000001
        min_bid_amount: 0.000001
    source:
      exchange_id: 2
      market:
        id: BTCUSDT
        base: BTC
        quote: USDT
        base_precision: 2
        quote_precision: 6
  - type: copy
    volume_ratio: 1
    delay: 30
    reload: 1
    spread_bids: 0
    spread_asks: 0
    limit_depth: 200
    target:
      exchange_id: 1
      market: 
        id: ETHUSDT
        base: ETH
        quote: USDT
        base_precision: 2
        quote_precision: 5
        min_ask_amount: 0.00001
        min_bid_amount: 0.00001
    source:
      exchange_id: 2
      market:
        id: ETHUSDT
        base: ETH
        quote: USDT
        base_precision: 2
        quote_precision: 5
  # - type: trade
  #   trade_amount: 10
  #   delay: 7
  #   target:
  #     exchange_id: 1
  #     market: 
  #       id: ETHUSDT
  #       base: ETH
  #       quote: USDT
  #       base_precision: 2
  #       quote_precision: 5
  #       min_ask_amount: 0.00001
  #       min_bid_amount: 0.00001
  #   source:
  #     exchange_id: 2
  #     market:
  #       id: ETHUSDT
  #       base: ETH
  #       quote: USDT
  #       base_precision: 2
  #       quote_precision: 5
