log_level: INFO

exchanges:
  - id: 1
    driver: zsmart
    host: "https://demo.zsmart.tech"
    ws: "wss://demo.zsmart.tech/api/v2/websocket"
    key: "eda20b00d5ea7041"
    secret: "1533439e383450ad30c8bda7a30326b6"

  - id: 2
    driver: binance
    host: "https://www.binance.com"
    ws: "wss://stream.binance.com:9443/ws"
    key: ""
    secret: ""

strategies:
  # - type: copy
  #   volume_ratio: 1
  #   delay: 2
  #   spread_bids: 0
  #   spread_asks: 0
  #   limit_depth: 100
  #   target:
  #     exchange_id: 1
  #     market: 
  #       id: ETHUSDT
  #       base: ETH
  #       quote: USDT
  #       base_precision: 2
  #       quote_precision: 5
  #       min_ask_amount: 0.00001
  #       min_bid_amount: 0.00001
  #   source:
  #     exchange_id: 2
  #     market:
  #       id: ETHUSDT
  #       base: ETH
  #       quote: USDT
  #       base_precision: 2
  #       quote_precision: 5
  - type: trade
    trade_amount: 5
    delay: 4
    target:
      exchange_id: 1
      market: 
        id: ETHUSDT
        base: ETH
        quote: USDT
        base_precision: 2
        quote_precision: 5
        min_ask_amount: 0.00001
        min_bid_amount: 0.00001
    source:
      exchange_id: 2
      market:
        id: ETHUSDT
        base: ETH
        quote: USDT
        base_precision: 2
        quote_precision: 5
