---
app:
  name: Z-Dax
  domain: zsmartex.com
  subdomain: www
render_protect: false
ssl:
  enabled: true
images:
  barong: barong
  peatio: peatio
  rango: rango
  kouda: kouda
  coverapp: zsmartex/coverapp:next
  castle: zsmartex/castle
storage:
  provider: AWS
  bucketName: zsmartex
  accessKey: changeme
  secretKey: changeme
twilio:
  phone_number: "+14159153078"
  account_sid: AC7901e689bbbf1ad92409186ac9ef6f71
  auth_token: 4c352b45d1e5dc5af8335e97f16fff7e
  service_id: MG093ddefd24da33eb3f93ba1834981a61
vault:
  root_token: s.hWSGlSrCPEXnMHe6AxUeI8G4
  peatio_rails_token: s.UsUJQYHtXbSxHgiPfVMDhehT
  peatio_crypto_token: s.AeNg2tAMCjG3j9C9llwWd96f
  peatio_upstream_token: s.4Sr5U0J4KlxFcxIuaVj85VDJ
  peatio_matching_token: s.EGHfcpUkVg5hQLzxdP6PJiUU
  barong_token: s.piBgaaUhEn8AYeaDYbqnaQqJ
  finex_engine_token: s.CDjv40McCqB1KCh6c108Vnow
database:
  host: db
  port: 5432
  user: zsmartex
  password: zsmartex
recaptcha:
  siteKey: changeme
  secretKey: changeme
smtp:
  host: smtp.zoho.com
  port: 587
  user: business@zsmart.tech
  password: zEH1WA4gZf9Y
  sender_email: business@zsmart.tech
  sender_name: ZSmartex
  sender_logo: https://i.imgur.com/hPhSOgu.png
daemons:
  blockchain: false
  deposit_address: true
  withdraw: false
  cron_jobs: true
  matching: true
  order_processor: true
  trade_executor: true
  mailer: false
  peatio_system_notify: true
  barong_system_notify: true
  code: true
