---
app:
  name: Z-Dax
  domain: zsmartex.tech
  subdomain: test
render_protect: false
ssl:
  enabled: true
images:
  barong: barong
  peatio: peatio
  rango: rango
  coverapp: zsmartex/coverapp:next
  castle: zsmartex/castle
storage:
  provider: AWS
  bucketName: zsmartex
  accessKey: changeme
  secretKey: changeme
twilio:
  phone_number: "+14159153078"
  account_sid: AC7901e689bbbf1ad92409186ac9ef6f71
  auth_token: 4c352b45d1e5dc5af8335e97f16fff7e
  service_id: MG093ddefd24da33eb3f93ba1834981a61
vault:
  root_token: s.yUjD7teE9xaUHty2IR8OGX7u
  peatio_rails_token: s.6JLC7sadFoq3e7nKf8kieGiB
  peatio_crypto_token: s.7SA5PdiloPUyZgWh8WkrdFo0
  peatio_upstream_token: s.CvgPqK5SqscQqhc0VWUlL1Gb
  peatio_matching_token: s.U9hLyUEAnJ3WWSW4j954GfMY
  barong_token: s.SOjsDJ79SHG244P4quz84dTk
  finex_engine_token: s.UNbqujRwArVxS7XG0DgZQIJt
database:
  host: yb-tserver-0
  port: 5433
  user: yugabyte
  password: yugabyte
recaptcha:
  siteKey: changeme
  secretKey: changeme
smtp:
  host: smtp.zoho.com
  port: 587
  user: business@zsmart.tech
  password: zEH1WA4gZf9Y
  sender_email: business@zsmart.tech
  sender_name: ZSmartex
  sender_logo: https://i.imgur.com/hPhSOgu.png
daemons:
  blockchain: false
  deposit: false
  deposit_coin_address: false
  withdraw_coin: false
  upstream: false
  cron_jobs: true
  matching: true
  order_processor: true
  trade_executor: true
  mailer: false
  ieo_order_processor: false
  ieo_order_executor: false
