---
app:
  name: Z-Dax
  domain: zsmartex.com
  subdomain: demo
render_protect: false
ssl:
  enabled: true
images:
  barong: zsmartex/barong
  peatio: zsmartex/peatio
  rango: zsmartex/rango
  kouda: zsmartex/kouda
  quantex: zsmartex/quantex
  coverapp: zsmartex/coverapp:dev
  castle: zsmartex/castle:dev
  mobiapp: zsmartex/mobiapp:dev
twilio:
  phone_number: "+14159153078"
  account_sid: AC7901e689bbbf1ad92409186ac9ef6f71
  auth_token: 4c352b45d1e5dc5af8335e97f16fff7e
  service_id: MG093ddefd24da33eb3f93ba1834981a61
vault:
  root_token: s.BEhOs13brODPCBOlVuvqhYfN
  peatio_token: s.wC4Pk5AnDaCtaBaAioXTIaRd
  peatio_crypto_token: s.YTWxZlAcV2phliiK3x0GaR90
  barong_token: s.f119kEJjloPKuq15wXqfpJ8J
  quantex_token: s.z2PSSaLxYiEfI2E5Vkj7d3F4
  quantex_runner_token: s.0gxrm7ZQWYTIVrNVNPMJpPmI
database:
  host: db
  port: 5432
  user: zsmartex
  password: zsmartex
recaptcha:
  siteKey: changeme
  secretKey: changeme
smtp:
  host: smtpout.secureserver.net
  port: 587
  user: business@system.zsmartex.com
  password: gdx_?3XM.B5?QSD
  sender_email: business@system.zsmartex.com
  sender_name: ZSmartex
  sender_logo: https://i.imgur.com/hPhSOgu.png
daemons:
  deposit_address: true
  withdraw: true
  cron_jobs: true
  matching: true
  order_processor: true
  trade_executor: true
  mailer: true
  peatio_system_notify: true
  barong_system_notify: true
  code: true
  peatio_grpc: true
  p2p: true
  conversation: true
  notify: true
  activity_recorder: true
