---
app:
  name: Z-Dax
  domain: zsmartex.com
  subdomain: demo
render_protect: false
ssl:
  enabled: true
images:
  barong: zsmartex/barong
  peatio: zsmartex/peatio
  rango: zsmartex/rango
  kouda: zsmartex/kouda
  quantex: zsmartex/quantex
  coverapp: zsmartex/coverapp:dev
  castle: zsmartex/castle:dev
  mobiapp: zsmartex/mobiapp:dev
twilio:
  phone_number: "+14159153078"
  account_sid: AC7901e689bbbf1ad92409186ac9ef6f71
  auth_token: 4c352b45d1e5dc5af8335e97f16fff7e
  service_id: MG093ddefd24da33eb3f93ba1834981a61
vault:
  root_token: s.K7Y2CI8bmBi0XbWr0uZo4GxU
  peatio_rails_token: s.3duQI5lTr8ItkomiOBWMaNFf
  peatio_crypto_token: s.mbhJDMRY2PxBe7LFuG2KLj6J
  barong_token: s.8wq5VSSgGzrERF4wWaQYmg3V
  quantex_token: s.DXWjgap5YyxwaH5YZWblMMP8
  quantex_runner_token: s.Jvugj4hIujLp3T6Dg00BKFd1
database:
  host: db
  port: 5432
  user: zsmartex
  password: zsmartex
recaptcha:
  siteKey: changeme
  secretKey: changeme
smtp:
  host: smtpout.secureserver.net
  port: 587
  user: business@zsmartex.com
  password: z6e#xG6YObV9
  sender_email: business@zsmartex.com
  sender_name: ZSmartex
  sender_logo: https://i.imgur.com/hPhSOgu.png
daemons:
  deposit_address: true
  withdraw: true
  cron_jobs: true
  matching: true
  order_processor: true
  trade_executor: true
  mailer: true
  peatio_system_notify: true
  barong_system_notify: true
  code: true
  peatio_grpc: true
  activity_recorder: true
