---
app:
  name: Z-Dax
  domain: zsmartex.io
  subdomain: www
render_protect: false
ssl:
  enabled: true
images:
  barong: zsmartex/barong
  peatio: zsmartex/peatio
  rango: zsmartex/rango
  kouda: zsmartex/kouda
  quantex: zsmartex/quantex
  coverapp: zsmartex/coverapp
  castle: zsmartex/castle
  mobiapp: zsmartex/mobiapp:dev
  mailer: zsmartex/mailer
twilio:
  phone_number: "+14159153078"
  account_sid: AC7901e689bbbf1ad92409186ac9ef6f71
  auth_token: 4c352b45d1e5dc5af8335e97f16fff7e
  service_id: MG093ddefd24da33eb3f93ba1834981a61
vault:
  root_token: s.rw3Uy3Q7Nwgsj5GEdus9k70w
  peatio_token: s.spuLSaTvbmRiohcaxCKLgAOx
  peatio_crypto_token: s.bQxuqcEWRRKVfPRJd233N1Bi
  barong_token: s.6zHYkkfwVtWkcorcSSJkUIwW
  quantex_token: s.tSgOkyVGSgeNanKEZZeqLu34
  quantex_runner_token: s.dLLKQIRAIKKh7vca4ddvBzxm
database:
  host: db
  port: 5432
  user: zsmartex
  password: zsmartex
recaptcha:
  siteKey: changeme
  secretKey: changeme
smtp:
  host: mail.spacemail.com
  port: 465
  user: business@zsmartex.io
  password: 79c7952F-50E5-412c-a63f-350dA2F40FA3
  sender_email: business@zsmartex.io
  sender_name: ZSmartex
  sender_logo: https://i.imgur.com/hPhSOgu.png
daemons:
  deposit_address: true
  withdraw: true
  cron_jobs: true
  matching: true
  order_processor: true
  trade_executor: true
  mailer: true
  peatio_system_notify: true
  barong_system_notify: true
  code: true
  peatio_grpc: true
  p2p: true
  conversation: true
  notify: true
  activity_recorder: true
