app:
  name: "Z-Dax"
  domain: "zsmart.tech"
  subdomain: "demo"
ssl:
  enabled: true
  email: "business@zsmart.tech"
image:
  barong: gcr.io/zsmartex/barong:2.6.5
  peatio: gcr.io/zsmartex/peatio:2.6.5
  rango: gcr.io/zsmartex/rango:2.6.0
  athena: gcr.io/zsmartex/athena:1.0.13
  contrive: gcr.io/zsmartex/contrive:1.0.4
storage:
  provider: "Google"
  bucketName: "zsmart"
  accessKey: "GOOGTQRI3JKKSPRV4XBKNPKZ"
  secretKey: "xoaBinmXXTV+E6J/dceV+60yY62kOHW/EKDZYdad"
terraform:
  credentials: "~/safe/zdax.json"
  project: "example-zdax"
  region: "europe-west4"
  zone: "europe-west4-a"
  instance_name: "zdax-cloud"
  machine_type: "n1-standard-4"
  image: "debian-cloud/debian-9"
twilio:
  phone_number: "+18577635282"
  account_sid: "AC9842e4cc2cfd0f21f93c7475f6d4723b"
  auth_token: "f3d3bc96dea477cf8a855608b1eb5951"
vault:
  url: http://vault:8200
  token: s.tRBAmlyVVRSgdensi7HUbSBU
recaptcha:
  siteKey: 6LcrA5wUAAAAABY8KW-beaUOjShGC_U2va3kJEJt
  secretKey: 6LcrA5wUAAAAAK53t5qrkC7wvMB1tBeJed2YEkMI
daemons:
  # Blockchain services
  withdraw_audit: true
  blockchain: true
  deposit_collection: true
  deposit_collection_fees: true
  deposit_coin_address: true
  withdraw_coin: true
  # Job
  influx_writer: true
  upstream: true
  cron_job: true
  # Job
  global_price: true
  # Matching engine
  matching: true
  order_processor: true
  trade_executor: true
sendgrid_api_key: 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
