---
app:
  name: Z-Dax
  domain: app.local
  subdomain: www
render_protect: false
ssl:
  enabled: false
  email: business@zsmart.tech
images:
  barong: quay.io/openware/barong:2.6.0-a97b181
  peatio: quay.io/openware/peatio:2.6.0-0f60e12
  athena: gcr.io/zsmartex/athena:1.0.13
  contrive: gcr.io/zsmartex/contrive:1.0.4
  finex: gcr.io/zsmartex/finex:1.0.20
storage:
  provider: Google
  bucketName: zsmart
  accessKey: GOOGTQRI3JKKSPRV4XBKNPKZ
  secretKey: xoaBinmXXTV+E6J/dceV+60yY62kOHW/EKDZYdad
twilio:
  phone_number: "+18577635282"
  account_sid: AC9842e4cc2cfd0f21f93c7475f6d4723b
  auth_token: f3d3bc96dea477cf8a855608b1eb5951
vault:
  token: s.CfOVE1RndthSibopJpcke7wS
database:
  host: db
  port: 5432
  user: root
  password: djtdjtdjtdjt
recaptcha:
  siteKey: 6LcrA5wUAAAAABY8KW-beaUOjShGC_U2va3kJEJt
  secretKey: 6LcrA5wUAAAAAK53t5qrkC7wvMB1tBeJed2YEkMI
smtp:
  host: smtp.sendgrid.net
  port: 2525
  user: apikey
  password: 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
  sender_email: no-reply@zsmart.tech
  sender_name: ZSmart
  sender_logo: https://media.giphy.com/media/khlyv0MvfDmKvbpzZO/giphy.gif
daemons:
  withdraw_audit: false
  blockchain: false
  deposit: false
  deposit_coin_address: false
  withdraw_coin: false
  upstream: false
  peatio_cron_job: true
  finex_cron_job: true
  matching: true
  order_processor: true
  trade_executor: true
  depth_cache: true
  mailer: false
