---
app:
  name: Z-Dax
  domain: zsmart.tech
  subdomain: demo
render_protect: false
ssl:
  enabled: true
  email: business@zsmart.tech
images:
  barong: registry.gitlab.com/zsmartex/barong:338d8656
  peatio: registry.gitlab.com/zsmartex/peatio:44a8d812
  rango: quay.io/openware/rango:3.0.2
storage:
  provider: AWS
  bucketName: zsmartex
  accessKey: AKIAULLC3J7NDE6SSFLK
  secretKey: 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
twilio:
  phone_number: "+18577635282"
  account_sid: AC9842e4cc2cfd0f21f93c7475f6d4723b
  auth_token: f3d3bc96dea477cf8a855608b1eb5951
vault:
  token: s.ceyd7yF0jNzCVC28oNNbo8E7
database:
  host: db
  port: 5432
  user: root
  password: changeme
recaptcha:
  siteKey: 6LcrA5wUAAAAABY8KW-beaUOjShGC_U2va3kJEJt
  secretKey: 6LcrA5wUAAAAAK53t5qrkC7wvMB1tBeJed2YEkMI
smtp:
  host: smtp.sendgrid.net
  port: 2525
  user: apikey
  password: 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
  sender_email: no-reply@zsmart.tech
  sender_name: ZSmart
  sender_logo: https://i.imgur.com/hPhSOgu.png
daemons:
  blockchain: true
  deposit: true
  deposit_coin_address: true
  withdraw_coin: true
  upstream: false
  peatio_cron_job: true
  finex_cron_job: true
  matching: true
  order_processor: true
  trade_executor: true
  mailer: true
