images:
  quantex: registry.gitlab.com/zsmartex/quantex:b9a9539d
  applogic: registry.gitlab.com/zsmartex/applogic:9841e3cf
  finex: registry.gitlab.com/zsmartex/finex:ca980591
quantex:
  log_level: DEBUG
  exchanges:
  - id: 1
    driver: zsmartex
    host: "http://www.app.local/api/v2/"
    ws: "ws://www.app.local/api/v2/websocket/private"
    key: "70f7a91a6b0414b1"
    secret: "e59463758546de92f4cef197c43127f1"
  - id: 2
    driver: binance
    host: "https://www.binance.com/"
    ws: "wss://stream.binance.com:9443/ws"
    key: ""
    secret: ""
  strategies:
  - id: 1
    type: copy
    enabled: true
    params:
      side: both
      enable_orderback: false # not ready
      limit_asks_base: 0.00001
      limit_bids_base: 0.00001
      flows:
      - id: 1
        period: 1
        spread_bids: 0.003
        spread_asks: 0.003
        levels_size: 0.25 # percent 25% = 0.25
        levels_count: 2
        levels_start: 10
      - id: 2
        period: 5
        spread_bids: 0.003
        spread_asks: 0.003
        levels_size: 0.25 # percent 25% = 0.25
        levels_count: 4
        levels_start: 40
      - id: 3
        period: 5
        spread_bids: 0.003
        spread_asks: 0.003
        levels_size: 0.25 # percent 25% = 0.25
        levels_count: 5
        levels_start: 60
      - id: 4
        period: 7
        spread_bids: 0.003
        spread_asks: 0.003
        levels_size: 0.25 # percent 25% = 0.25
        levels_count: 4
        levels_start: 1200
      - id: 5
        period: 15
        spread_bids: 0.003
        spread_asks: 0.003
        levels_size: 0.25 # percent 25% = 0.25
        levels_count: 20
        levels_start: 2500
      - id: 6
        period: 57
        spread_bids: 0.003
        spread_asks: 0.003
        levels_size: 0.25 # percent 25% = 0.25
        levels_count: 20
        levels_start: 3000
      - id: 7
        period: 43
        spread_bids: 0.003
        spread_asks: 0.003
        levels_size: 0.25 # percent 25% = 0.25
        levels_count: 40
        levels_start: 4000
    target:
      exchange_id: 1
      market:
        id: ETHUSDT
        base: ETH
        quote: USDT
        base_precision: 2
        quote_precision: 5
    sources:
    - exchange_id: 2
      market:
        id: ETHUSDT
        base: ETH
        quote: USDT
        base_precision: 2
        quote_precision: 5
  - id: 2
    type: trade
    enabled: true
    params:
      side: both
      flows:
      - id: 1
        period: 15
        limit_asks_base: 0.00001
        limit_bids_base: 0.00001
    target:
      exchange_id: 1
      market:
        id: ETHUSDT
        base: ETH
        quote: USDT
        base_precision: 2
        quote_precision: 5
    sources:
    - exchange_id: 2
      market:
        id: ETHUSDT
        base: ETH
        quote: USDT
        base_precision: 2
        quote_precision: 5
  - id: 3
    type: copy
    enabled: true
    params:
      side: both
      enable_orderback: false # not ready
      limit_asks_base: 0.00001
      limit_bids_base: 0.00001
      flows:
      - id: 1
        period: 1
        spread_bids: 0.003
        spread_asks: 0.003
        levels_size: 0.25 # percent 25% = 0.25
        levels_count: 2
        levels_start: 10
      - id: 2
        period: 5
        spread_bids: 0.003
        spread_asks: 0.003
        levels_size: 0.25 # percent 25% = 0.25
        levels_count: 4
        levels_start: 40
      - id: 3
        period: 5
        spread_bids: 0.003
        spread_asks: 0.003
        levels_size: 0.25 # percent 25% = 0.25
        levels_count: 5
        levels_start: 60
      - id: 4
        period: 7
        spread_bids: 0.003
        spread_asks: 0.003
        levels_size: 0.25 # percent 25% = 0.25
        levels_count: 4
        levels_start: 1200
      - id: 5
        period: 15
        spread_bids: 0.003
        spread_asks: 0.003
        levels_size: 0.25 # percent 25% = 0.25
        levels_count: 20
        levels_start: 2500
      - id: 6
        period: 57
        spread_bids: 0.003
        spread_asks: 0.003
        levels_size: 0.25 # percent 25% = 0.25
        levels_count: 20
        levels_start: 3000
      - id: 7
        period: 43
        spread_bids: 0.003
        spread_asks: 0.003
        levels_size: 0.25 # percent 25% = 0.25
        levels_count: 40
        levels_start: 4000
    target:
      exchange_id: 1
      market:
        id: BTCUSDT
        base: BTC
        quote: USDT
        base_precision: 2
        quote_precision: 5
    sources:
    - exchange_id: 2
      market:
        id: BTCUSDT
        base: BTC
        quote: USDT
        base_precision: 2
        quote_precision: 5
  - id: 4
    type: trade
    enabled: true
    params:
      side: both
      limit_asks_base: 0.00001
      limit_bids_base: 0.00001
      flows:
      - id: 1
        period: 15
    target:
      exchange_id: 1
      market:
        id: BTCUSDT
        base: BTC
        quote: USDT
        base_precision: 2
        quote_precision: 5
    sources:
    - exchange_id: 2
      market:
        id: BTCUSDT
        base: BTC
        quote: USDT
        base_precision: 2
        quote_precision: 5
