- id: btcusdt
  base_unit: btc
  quote_unit: usdt
  amount_precision: 5
  price_precision: 2
  total_precision: 5
  state: enabled
  min_price: 10
  max_price: 0
  min_amount: 0.0001
  position: 1

- id: ethusdt
  base_unit: eth
  quote_unit: usdt
  amount_precision: 4
  price_precision: 2
  total_precision: 5
  state: enabled
  min_price: 10
  max_price: 0
  min_amount: 0.001
  position: 2

- id: bnbusdt
  base_unit: bnb
  quote_unit: usdt
  amount_precision: 3
  price_precision: 1
  total_precision: 2
  state: enabled
  min_price: 10
  max_price: 0
  min_amount: 0.01
  position: 3

- id: trxusdt
  base_unit: trx
  quote_unit: usdt
  amount_precision: 1
  price_precision: 5
  total_precision: 3
  state: enabled
  min_price: 0.0001
  max_price: 0
  min_amount: 5
  position: 4

- id: dogeusdt
  base_unit: doge
  quote_unit: usdt
  amount_precision: 0
  price_precision: 5
  total_precision: 3
  state: enabled
  min_price: 0.00001
  max_price: 0
  min_amount: 5
  position: 5
