keychain:
  applogic:
    algorithm: RS256
    value: LS0tLS1CRUdJTiBQVUJMSUMgS0VZLS0tLS0KTUlJQklqQU5CZ2txaGtpRzl3MEJBUUVGQUFPQ0FROEFNSUlCQ2dLQ0FRRUE2eWE0a3FoL01vd1VWNjA4NWFkYwpnS0ZLaFN4SkN2ZFNHY0JsWEFpOW15SW51RlgxNG5NS1JMbWpXZFlvRFZvWXdjUmNoT0JNQWhkQkw4YnAyQkY5CkgwV1d3YXV1Y3hFOGdDV1ArVzJFRUVlZVRHb0I4c0EzMlNQVDcvb0s0T1doVVMzR0ptK3c0WERucTl1T3BmMlMKQnpFZFM4YlZ2ZmU3cWEwcHVZWWhkZzlqTlZHdVhDMWlFR2Q2bXdqMXdsVTVxLzdKdU1laTNRK0xMd1F1UTYrSwptNEs0REF4UTdPYnVONDN3b3ZBNWI0MmxuTExkcFhLSGlmbXhMTEVBa3B6VWhiWGdkRE5MTTNBMTAyWTN4NndSCkJObGVZWkp2RDYzL3JsSGxGcGZIVGdhZWtsYTJEVzl1bG1vaStsY2V5dFJmN1dPT3orVmVCY3h0RnBROTJTUHEKMFFJREFRQUIKLS0tLS1FTkQgUFVCTElDIEtFWS0tLS0tCg==
    
scopes:
  read_users:
    mandatory_signers:
      - applogic
    permitted_signers:
      - applogic
  read_labels:
    mandatory_signers:
      - applogic
    permitted_signers:
      - applogic
  write_labels:
    mandatory_signers:
      - applogic
    permitted_signers:
      - applogic
  tools:
    mandatory_signers:
      - applogic
    permitted_signers:
      - applogic
