keychain:
  applogic:
    algorithm: RS256
    value: LS0tLS1CRUdJTiBQVUJMSUMgS0VZLS0tLS0KTUlJQklqQU5CZ2txaGtpRzl3MEJBUUVGQUFPQ0FROEFNSUlCQ2dLQ0FRRUF3ajdyY1dERjl0d1RPZmt6RHlIZQpEdjlyWDZIQnJEa1VUSklsVmQzNnk0dnIvU1pkdDhkTFdidUxlb0ZtaHdNK1BGWnNubVJhYzljeHB4cmJsV0Q2CmdsN1B6RFNpK1NYTGFPOVdmY0lJYlM2a1cxT3ViclZoRTg4VUFZLzlIREUxbWZ1ZzJUVmtWMmRCSFU1dGwxZDAKTEZqOHVMa3Y0ZUozREVRb1RHdUk0UHBFN3hxTDBzNndabmo1VXArcUNDRmpzNWpPTWUrV0h2YTlhRVhTVU1GVgpvYkFSVnB1S3VQSUQ0SW1xMEJ1THlLMlJZRDRuY1RMSmRGVUQ3K3VuQ044Rm1PUXNYMy9pcENUclV0dlVxWHNpCk16WW9pdExqNkpMalI3S3FMbENicjdRMGlwZHFyMWNaT0Z0ZVpydU1JcHNaYnJvZHNKRis0QnMvMk9SMUdNSkQKY3dJREFRQUIKLS0tLS1FTkQgUFVCTElDIEtFWS0tLS0tCg==
    
scopes:
  read_users:
    mandatory_signers:
      - applogic
    permitted_signers:
      - applogic
